# /**
#  * GLX: Connect the World - Civic Networking Platform
#  * 
#  * Copyright (c) 2025 rsl37
#  * Dual-licensed under PolyForm Shield 1.0.0 OR PolyForm Noncommercial 1.0.0
#  * 
#  * ⚠️  TERMS:
#  * - Commercial use strictly prohibited without written permission from copyright holder
#  * - Forking/derivative works prohibited without written permission
#  * - Violations subject to legal action and damages
#  * 
#  * See LICENSE file in repository root for full terms.
#  * Contact: roselleroberts@pm.me for licensing inquiries
#  */

# YAML Lint Configuration for GitHub Actions Workflows
# This configuration accommodates longer lines in workflows for table formatting
# and complex expressions commonly used in GitHub Actions

extends: default

rules:
  line-length:
    max: 250  # Increased for GitHub Actions STEP_SUMMARY tables
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
    check-keys: false

  comments:
    min-spaces-from-content: 1

  trailing-spaces: enable
  new-line-at-end-of-file: enable
  empty-lines:
    max: 1
    max-end: 1
    max-start: 0
